# -----------------------------------------------------------------------------
# BSD 3-Clause License
#
# Copyright (c) 2026, Science and Technology Facilities Council.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# -----------------------------------------------------------------------------

"""The compile-time array a captured region carries rather than takes.

Split out rather than added to
:py:mod:`psyclone.psyir.backend.kokkos`, which is at the size a module of
this project may reach; the region descriptions there move out wholesale in a
later change and this one starts where they are going.
"""

from dataclasses import dataclass
from typing import Tuple, Union

from psyclone.psyir.nodes import Node


@dataclass(frozen=True)
class KokkosConstant:
    """A compile-time array declared at file scope in the generated unit.

    A Fortran ``parameter`` array declared beside the kernel body -- ``integer
    (i_def), parameter :: x_dofs(2) = (/ 1, 3 /)`` -- states its own values,
    so the region carries them and adds no formal to the C ABI. Its subscripts
    are C's, and ``index_offsets`` removes the declared origin from each
    exactly as a View's does; ``extra_indices`` is carried and always empty,
    so that one array-reference table holds Views, scratch and constants
    alike.
    """

    name: str
    c_type: str
    #: The value of each element, in the order the Fortran declared them.
    #: Generated by the writer rather than held as text, so that a literal
    #: takes the region's own width rather than the C writer's default.
    values: Tuple[Node, ...]
    #: As :py:attr:`psyclone.psyir.backend.kokkos.KokkosView.index_offsets`.
    index_offsets: Tuple[Union[int, str], ...] = ()
    extra_indices: Tuple[str, ...] = ()


__all__ = ["KokkosConstant"]
